### ISSUE TITLE
Error accessing PA on Cloud

### ISSUE THREAD

**Issue by psegal** [ykud/tm1cmp#4]
Hi Ykud,

Appreciate it's an imposition, but I don't see where I'm going wrong here and could use some help. I have an On Prem Server and PA on Cloud (same TM1 server name), and it would be great to use this to compare identical views. The On Prem seems to go fine, but I have a 404 error on the Cloud instance. Config, schema and log files attached.

Regards

Paul

[checkfile.txt](https://github.com/ykud/tm1cmp/files/4927746/checkfile.txt)
[config.txt](https://github.com/ykud/tm1cmp/files/4927747/config.txt)
[tm1cmp_20200715-211716.log](https://github.com/ykud/tm1cmp/files/4927748/tm1cmp_20200715-211716.log)

@ykud

**Comment by psegal** [comment]
adding @ykud so you see this!

**Comment by silw** [comment]
Hey @psegal 

try 

base_url=https://crane.planning-analytics.ibmcloud.com/tm1/api/jcg/

Cheers,
Fedor

**Comment by psegal** [comment]
Hi Fedor,

No dice, I'm afraid. Adding the / gives me 

Not Found
--
 
The requested URL   /tm1/api/jcg//api/v1/Configuration/ProductVersion/$value was not found on   this server.

Without the / seems better formed, but still the same Not Found error:

</head><body>
<h1>Not Found</h1>
<p>The requested URL /tm1/api/jcg/api/v1/Configuration/ProductVersion/$value was not found on this server.</p>
</body></html>
 Status Code: 404 Reason: Not Found Headers: {'Date': 'Thu, 16 Jul 2020 13:29:33 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Type': 'text/html; charset=iso-8859-1', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'X-Content-Type-Options': 'nosniff', 'Content-Length': '216', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive'}


Regards

Paul

@silw

**Comment by silw** [comment]
Paul, 

and what is the TM1 instance name? jcg or JCG? case matters.

Cheers,
Fedor

**Comment by psegal** [comment]
Hi Fedor,

Ah, that was it. I'm so used to case not mattering.

Thank you!

Regards,

Paul
